export const EMAIL_VERIFICATION_TOKEN_BYTES = 32;
export const EMAIL_VERIFICATION_TOKEN_TTL_MS = 30 * 60_000;
export const EMAIL_VERIFICATION_TOKEN_MAX_LENGTH = 128;

export const EMAIL_VERIFICATION_DELIVERY_TIMEOUT_MS = 5_000;
export const RESEND_EMAIL_ENDPOINT = 'https://api.resend.com/emails';
