import {
  generateCssVariablesExport,
  type CssVariablesExportTheme,
  type CssVariablesExportSkippedToken,
} from './css-variables-export';
import type { DesignToken } from '@/domain/design-system';

export type TailwindV4ExportInput = {
  projectName: string;
  tokens: readonly DesignToken[];
  themes?: readonly CssVariablesExportTheme[];
  includeDeprecated?: boolean;
};

export type TailwindThemeVariable = {
  path: string;
  cssVariableName: string;
  tailwindName: string;
  value: string;
};

export type TailwindV4ExportResult = {
  fileName: string;
  content: string;
  variables: TailwindThemeVariable[];
  skippedTokens: CssVariablesExportSkippedToken[];
};

function toKebabCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function createTailwindFileName(projectName: string): string {
  return `${toKebabCase(projectName) || 'design-system'}-tailwind.css`;
}

export function tokenPathToTailwindThemeName(path: string): string {
  return `--${path
    .split('.')
    .map(toKebabCase)
    .filter((segment) => segment.length > 0)
    .join('-')}`;
}

function renderThemeBlock(variables: readonly TailwindThemeVariable[]): string {
  if (variables.length === 0) {
    return '';
  }

  const declarations = variables
    .map(
      (variable) =>
        `  ${variable.tailwindName}: var(${variable.cssVariableName});`,
    )
    .join('\n');

  return ['@theme {', declarations, '}'].join('\n');
}

export function generateTailwindV4Export({
  projectName,
  tokens,
  themes = [],
  includeDeprecated = false,
}: TailwindV4ExportInput): TailwindV4ExportResult {
  const cssVariablesExport = generateCssVariablesExport({
    projectName,
    tokens,
    themes,
    includeDeprecated,
  });

  const rootTokenVariables = cssVariablesExport.variables.filter(
    (variable) => variable.scope === ':root',
  );

  const variables = rootTokenVariables.map((variable) => ({
    path: variable.path,
    cssVariableName: variable.name,
    tailwindName: tokenPathToTailwindThemeName(variable.path),
    value: variable.value,
  }));

  const content = [
    `/* ${projectName} — Tailwind v4 theme */`,
    '/* generated by VulcanForgeUI · do not edit manually */',
    '',
    cssVariablesExport.content,
    '',
    renderThemeBlock(variables),
  ]
    .filter((section) => section.trim().length > 0)
    .join('\n\n')
    .trim();

  return {
    fileName: createTailwindFileName(projectName),
    content,
    variables,
    skippedTokens: cssVariablesExport.skippedTokens,
  };
}
