import {
  generateCssVariablesExport,
  type CssVariablesExportTheme,
  type CssVariablesExportSkippedToken,
} from './css-variables-export';
import type { DesignToken } from '@/domain/design-system';

export type TypeScriptThemeExportInput = {
  projectName: string;
  tokens: readonly DesignToken[];
  themes?: readonly CssVariablesExportTheme[];
  includeDeprecated?: boolean;
};

export type TypeScriptThemeExportResult = {
  fileName: string;
  content: string;
  tokens: Record<string, unknown>;
  themes: Record<string, Record<string, unknown>>;
  skippedTokens: CssVariablesExportSkippedToken[];
};

type PrimitiveThemeValue = string | number | boolean;

type FlattenedThemeToken = {
  path: string;
  value: PrimitiveThemeValue;
};

function toKebabCase(value: string): string {
  return value
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

function toCamelCase(value: string): string {
  const normalizedValue = toKebabCase(value);

  return normalizedValue.replace(/-([a-z0-9])/g, (_, character: string) =>
    character.toUpperCase(),
  );
}

function createTypeScriptFileName(projectName: string): string {
  return `${toKebabCase(projectName) || 'design-system'}-theme.ts`;
}

function pathToObjectKey(pathSegment: string): string {
  const normalizedSegment = toCamelCase(pathSegment);

  return /^\d/.test(normalizedSegment)
    ? `_${normalizedSegment}`
    : normalizedSegment;
}

function setNestedValue({
  target,
  path,
  value,
}: {
  target: Record<string, unknown>;
  path: string;
  value: unknown;
}) {
  const segments = path.split('.').map(pathToObjectKey);
  let currentTarget = target;

  segments.forEach((segment, index) => {
    const isLeaf = index === segments.length - 1;

    if (isLeaf) {
      currentTarget[segment] = value;
      return;
    }

    const existingValue = currentTarget[segment];

    if (
      !existingValue ||
      typeof existingValue !== 'object' ||
      Array.isArray(existingValue)
    ) {
      currentTarget[segment] = {};
    }

    currentTarget = currentTarget[segment] as Record<string, unknown>;
  });
}

function flattenThemeTokens(
  tokens: Record<string, unknown>,
  prefix: string[] = [],
): FlattenedThemeToken[] {
  return Object.entries(tokens).flatMap(([key, value]) => {
    const nextPath = [...prefix, key];

    if (
      typeof value === 'string' ||
      typeof value === 'number' ||
      typeof value === 'boolean'
    ) {
      return [
        {
          path: nextPath.join('.'),
          value,
        },
      ];
    }

    if (value && typeof value === 'object' && !Array.isArray(value)) {
      return flattenThemeTokens(value as Record<string, unknown>, nextPath);
    }

    return [];
  });
}

function createTokensObject({
  projectName,
  tokens,
  includeDeprecated,
}: {
  projectName: string;
  tokens: readonly DesignToken[];
  includeDeprecated: boolean;
}) {
  const cssVariablesExport = generateCssVariablesExport({
    projectName,
    tokens,
    includeDeprecated,
  });

  const resolvedTokens: Record<string, unknown> = {};

  cssVariablesExport.variables.forEach((variable) => {
    setNestedValue({
      target: resolvedTokens,
      path: variable.path,
      value: variable.value,
    });
  });

  return {
    tokens: resolvedTokens,
    skippedTokens: cssVariablesExport.skippedTokens,
  };
}

function createThemesObject(themes: readonly CssVariablesExportTheme[]) {
  return themes.reduce<Record<string, Record<string, unknown>>>(
    (themeMap, theme) => {
      const themeTokens: Record<string, unknown> = {};

      flattenThemeTokens(theme.tokens).forEach((token) => {
        setNestedValue({
          target: themeTokens,
          path: token.path,
          value: token.value,
        });
      });

      themeMap[theme.mode] = themeTokens;

      return themeMap;
    },
    {},
  );
}

function serializeAsConst(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

export function generateTypeScriptThemeExport({
  projectName,
  tokens,
  themes = [],
  includeDeprecated = false,
}: TypeScriptThemeExportInput): TypeScriptThemeExportResult {
  const resolvedTokenResult = createTokensObject({
    projectName,
    tokens,
    includeDeprecated,
  });

  const themeMap = createThemesObject(themes);

  const content = [
    `// ${projectName} — TypeScript theme`,
    '// generated by VulcanForgeUI · do not edit manually',
    '',
    `export const tokens = ${serializeAsConst(resolvedTokenResult.tokens)} as const;`,
    '',
    `export const themes = ${serializeAsConst(themeMap)} as const;`,
    '',
    'export const designSystemTheme = {',
    '  tokens,',
    '  themes,',
    '} as const;',
    '',
    'export type DesignSystemTokens = typeof tokens;',
    'export type DesignSystemThemes = typeof themes;',
    'export type DesignSystemTheme = typeof designSystemTheme;',
    '',
    'export default designSystemTheme;',
  ].join('\n');

  return {
    fileName: createTypeScriptFileName(projectName),
    content,
    tokens: resolvedTokenResult.tokens,
    themes: themeMap,
    skippedTokens: resolvedTokenResult.skippedTokens,
  };
}
