import { describe, expect, it } from 'vitest';
import { tokenizeAiInstructionsLine } from './AiInstructionsCodePreview';

function compactTokens(
  tokens: ReturnType<typeof tokenizeAiInstructionsLine>,
): Array<[string, string]> {
  return tokens
    .filter((token) => token.value.length > 0)
    .map((token) => [token.kind, token.value]);
}

describe('tokenizeAiInstructionsLine', () => {
  it('highlights Markdown headings', () => {
    expect(compactTokens(tokenizeAiInstructionsLine('## Token rules'))).toEqual(
      [
        ['marker', '## '],
        ['heading', 'Token rules'],
      ],
    );
  });

  it('highlights list markers and inline model values', () => {
    expect(
      compactTokens(
        tokenizeAiInstructionsLine(
          '- Use `color.semantic.background.app` for page backgrounds.',
        ),
      ),
    ).toEqual([
      ['marker', '- '],
      ['plain', 'Use '],
      ['value', '`color.semantic.background.app`'],
      ['plain', ' for page backgrounds.'],
    ]);
  });

  it('treats generated comments as muted content', () => {
    expect(
      compactTokens(
        tokenizeAiInstructionsLine(
          '<!-- generated by VulcanForgeUI · strict · do not edit -->',
        ),
      ),
    ).toEqual([
      ['comment', '<!-- generated by VulcanForgeUI · strict · do not edit -->'],
    ]);
  });
});
